stages:
  - build
  - test
  - lint

image: brndnmtthws/conky-builder:latest
variables:
  CC: clang-7
  CXX: clang++-7

build:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4

test:
  script:
    - cd build
    - make test

lint:
  script:
    - cd build
    - cmake -DCHECK_CODE_QUALITY=ON ..
    - make check
