name: 🐞 Bug Report
description: "File a bug report: crashes, unexpected behaviour, and other errors go here."
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        If you haven't done so already, please take a moment to search the
        [existing issues](https://github.com/brndnmtthws/conky/issues) to see if
        this has been previously reported. If not, carry on.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Describe the problem, what you expected to happen, and any other
        relevant info. You can attach logs, stack traces, and config below. If
        required, include screenshots here which demonstrate the problem.
      placeholder: Here's what happened
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Conky are you running?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Which OS/distro are you seeing the problem on?
      options:
        - Ubuntu
        - Fedora
        - Debian
        - Arch Linux
        - Gentoo
        - Linux (other)
        - macOS
  - type: textarea
    id: config
    attributes:
      label: Conky config
      description: Paste your Conky config here if it's relevant.
      render: Lua
  - type: markdown
    attributes:
      value: |
        ## Getting a stack trace
        If you want to report a crash, please attach a stack trace.

        To create one with `gdb`, try the following steps:

        ```shell
        # Start 'conky'
        $ gdb conky

        # Run 'conky' with a config.
        (gdb) run -c ~/.your_conky.conf

        # Wait for a crash to occur, then run this.
        (gdb) bt full

        # ... stack trace output here ...
        ```

        We want that backtrace inside `gdb` triple backticks.

        ```gdb
        $ gdb conky
        GNU gdb (GDB) 8.2
        Copyright (C) 2018 Free Software Foundation, Inc.
        License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
        This is free software: you are free to change and redistribute it.
        There is NO WARRANTY, to the extent permitted by law.
        ...
        ```
  - type: textarea
    id: stacktrace
    attributes:
      label: Stack trace
      description: Paste your stacktrace here, if required.
      render: Shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
